### ISSUE TITLE
Migrate `addon/` to `addon-test-support/`.

### ISSUE THREAD

**Issue by rwjblue** [salsify/ember-cli-pact#17]
The `addon-test-support/` tree automatically gets added to the `test-support.js` asset (as opposed to `vendor.js`).  By default, these assets are transpiled to `<addon-name>/test-support`, but you can easily modify that to remove the `/test-support` suffix if the addon is "test only" (see [ember-test-helpers](https://github.com/emberjs/ember-test-helpers/blob/master/index.js) for an example).

**Comment by dfreeman** [comment]
Ah yep, I even knew that there were addons that did that and I just spaced when I was working on the 'inert in production' stuff 👍

**Comment by dfreeman** [comment]
Thanks to @acdn-sglanzer this migration has happened to the degree it's going to — things relying on `@ember/test-helpers` are now part of the `addon-test-support` tree, but bits that are potentially referenced in development (e.g. Mirage-related stuff) have remained in `addon` so things don't 💥
