### ISSUE TITLE
Conflict between how ember-cli-pact tags version and how the ruby pact-support parses version

### ISSUE THREAD

**Issue by psbanka** [salsify/ember-cli-pact#29]
I wanted to log the issue here for visibility, as this appears to be an issue with Ruby's [pact-support](https://github.com/pact-foundation/pact-support) Gem, but it might be good for folks here to know that the pact files that ember-cli-pact generates are currently **incompatible** with pact verification on Ruby systems if they are using the official `pact-support` Gem.

https://github.com/pact-foundation/pact-support/issues/62

**Comment by psbanka** [comment]
In fact, the ruby-pact people are asking that we use `pactSpecification` and not `pact-specification` (https://github.com/pact-foundation/pact-support/issues/62)

**Comment by bethesque** [comment]
Please use `pactSpecification` - the `pact-specification` was a historical error.

**Comment by dfreeman** [comment]
Thanks @psbanka and @bethesque! Fixed by #30.
