### ISSUE TITLE
Matching rule for all elements

### ISSUE THREAD

**Issue by afriqs** [salsify/ember-cli-pact#37]
Hi,

I don't really understand how to configure the matching rules to check all the items of an array. 

Let's say for example that we are fetching a list of *articles*, each with a *title*. How can we configure it to have a resulting `$.data[*].attributes.title` ?

According to the [doc](https://github.com/salsify/ember-cli-pact#matchers) I may use `arrayElements(matcher)` but I don't find out how to :blush: . I tried :

```
    specifyMatchingRules({
      response: {
        body: {
          data: {
            attributes: {
              title: arrayElements[type()],
            }
          }
        }
      }
    })
```

**Comment by dfreeman** [comment]
Hi @afriqs,

The docs are a little sparse, but you can see a bunch of examples of the expected output for matchers in [the matching-rules unit test](https://github.com/salsify/ember-cli-pact/blob/master/tests/unit/-private/matching-rules-test.js).

For your specific question here, the `arrayElements` matcher goes at the level where you're expecting to see an array, e.g.

```ts
specifyMatchingRules({
  response: {
    body: {
      data: arrayElements({
        attributes: {
          title: type()
        }
      })
    }
  }
});
```

**Comment by afriqs** [comment]
Thanks @dfreeman for your quick answer and I confirm it produces such code : 
```
"matchingRules": {
  "$.body.data[*].attributes.title": {
    "match": "type"
  }
},
```

I think I was misled by the expression `arrayElements(matcher)`: for me it was expected matchers and not elements with matchers :relaxed: 

Unfortunately the gem I use on the API side does not understand `$.body.data[*].attributes.title` but expects `$.body.data[*].attributes.title`, `$.body.data[*].attributes.title`, etc., but this is not an *ember-cli-pact* issue :wink:
